# Generated by Django 3.1 on 2020-09-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expositor',
            old_name='email',
            new_name='email_expositor',
        ),
    ]
